# Generated by Django 4.1.6 on 2023-02-13 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
